name: .NET Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore VideojuegoServidor/VideojuegoServidor.sln
        dotnet restore VideojuegoCliente/VideojuegoCliente.sln

    - name: Build Server Solution
      run: dotnet build VideojuegoServidor/VideojuegoServidor.sln --no-restore

    - name: Build Client Solution
      run: dotnet build VideojuegoCliente/VideojuegoCliente.sln --no-restore
